import type { Metadata } from 'next';
import MSWProvider from '@/app/_components/common/MswProvider';
import JotaiProvider from '@/app/_components/common/JotaiProvider';
import GlobalLayout from './_components/layout/GlobalLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <JotaiProvider>
          <MSWProvider>
            <GlobalLayout>{children}</GlobalLayout>
          </MSWProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
