import type { Metadata } from 'next';
import MSWProvider from '@/app/_components/common/MswProvider';
import JotaiProvider from '@/app/_components/common/JotaiProvider';
import NavigateBar from './_components/nav/Navigate';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <JotaiProvider>
          <NavigateBar />
          <MSWProvider>{children}</MSWProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
