name: Create Branch For Issue
on:
  issues:
    types: [assigned]
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      issues: write
      pull-requests: write
      attestations: write
      checks: write
      contents: write
      deployments: write
      discussions: write
      packages: write
      pages: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
